# Generated by Django 5.0.6 on 2024-07-10 23:39

import django.db.models.deletion
import homework.models
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("homework", "0001_initial"),
        ("homework", "0002_alter_homework_description_alter_homework_grade_and_more"),
        ("homework", "0003_file_alter_image_image_path_homework_file"),
        ("homework", "0004_remove_homework_file_remove_homework_image_and_more"),
        ("homework", "0005_rename_file_path_file_file"),
        ("homework", "0006_alter_file_homework"),
        ("homework", "0007_file_file_name"),
        ("homework", "0008_alter_file_file_name"),
        ("homework", "0009_alter_file_homework_alter_image_homework"),
        ("homework", "0010_alter_homework_grade_alter_homework_letter"),
        ("homework", "0011_homework_subject_alter_homework_grade"),
        ("homework", "0012_alter_homework_letter"),
        ("homework", "0013_homework_group"),
        ("homework", "0014_alter_homework_created_at"),
        ("homework", "0015_alter_homework_group"),
        (
            "homework",
            "0016_alter_homework_created_at_alter_homework_description_and_more",
        ),
        ("homework", "0017_alter_file_options_alter_homework_options_and_more"),
        ("homework", "0018_todo_homework_todo"),
        ("homework", "0019_alter_homework_todo"),
        ("homework", "0020_todo_created_at"),
        ("homework", "0021_alter_homework_letter"),
    ]

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Homework",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grade",
                    models.IntegerField(
                        choices=[
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                            (11, 11),
                        ],
                        verbose_name="Класс",
                    ),
                ),
                (
                    "letter",
                    models.CharField(
                        choices=[("А", "А"), ("Б", "Б"), ("Г", "В"), ("Г", "Г")],
                        verbose_name="Буква",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "created_at",
                    homework.models.DateTimeWithoutTZField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                ("subject", models.CharField(null=True, verbose_name="Предмет")),
                (
                    "group",
                    models.IntegerField(
                        choices=[(-3, -3), (-2, -2), (-1, -1), (0, 0), (1, 1), (2, 2)],
                        default=0,
                        verbose_name="Группа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Домашнее задание",
                "verbose_name_plural": "Домашние задания",
            },
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        null=True,
                        upload_to="files/homework/%Y/%d-%m/",
                        verbose_name="Путь к файлу",
                    ),
                ),
                (
                    "homework",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="homework.homework",
                        verbose_name="Домашнее задание",
                    ),
                ),
                ("file_name", models.CharField(verbose_name="Название файлы")),
            ],
            options={
                "verbose_name": "Файл",
                "verbose_name_plural": "Файлы",
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "homework",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="homework.homework",
                        verbose_name="Домашнее задание",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        null=True,
                        upload_to="img/homework/%Y/%d-%m/",
                        verbose_name="Путь к изображению",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение",
                "verbose_name_plural": "Изображения",
            },
        ),
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_done",
                    models.BooleanField(default=False, verbose_name="Выполнено"),
                ),
                (
                    "created_at",
                    homework.models.DateTimeWithoutTZField(
                        auto_now_add=True,
                        default="2024-12-12",
                        verbose_name="Дата создания",
                    ),
                ),
            ],
            options={
                "verbose_name": "Список ToDo",
                "verbose_name_plural": "Списки ToDo",
            },
        ),
        migrations.AddField(
            model_name="homework",
            name="todo",
            field=models.ManyToManyField(related_name="homework", to="homework.todo"),
        ),
        migrations.AlterField(
            model_name="homework",
            name="letter",
            field=models.CharField(
                choices=[("А", "А"), ("Б", "Б"), ("Г", "В"), ("Г", "Г")],
                verbose_name="Литера",
            ),
        ),
    ]
