# Generated by Django 5.0.6 on 2024-07-01 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homework", "0003_file_alter_image_image_path_homework_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homework",
            name="file",
        ),
        migrations.RemoveField(
            model_name="homework",
            name="image",
        ),
        migrations.RemoveField(
            model_name="image",
            name="image_path",
        ),
        migrations.AddField(
            model_name="file",
            name="homework",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="homework",
                to="homework.homework",
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="homework",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="images",
                to="homework.homework",
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="image",
            field=models.ImageField(null=True, upload_to="img/homework/%Y/%d-%m/"),
        ),
        migrations.AlterField(
            model_name="file",
            name="file_path",
            field=models.FileField(null=True, upload_to="files/homework/%Y/%d-%m/"),
        ),
    ]
