# Generated by Django 5.0.6 on 2024-07-01 12:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("homework", "0004_remove_homework_file_remove_homework_image_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="file",
            old_name="file_path",
            new_name="file",
        ),
    ]
