# Generated by Django 5.0.6 on 2024-07-01 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homework", "0005_rename_file_path_file_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="homework",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="files",
                to="homework.homework",
            ),
        ),
    ]
