# Generated by Django 5.0.6 on 2024-07-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homework", "0006_alter_file_homework"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="file_name",
            field=models.CharField(default="1"),
        ),
    ]
