# Generated by Django 5.0.6 on 2024-07-01 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homework", "0008_alter_file_file_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="homework",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="homework.homework",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="homework",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="homework.homework",
            ),
        ),
    ]
