# Generated by Django 5.0.6 on 2024-07-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homework", "0010_alter_homework_grade_alter_homework_letter"),
    ]

    operations = [
        migrations.AddField(
            model_name="homework",
            name="subject",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="homework",
            name="grade",
            field=models.IntegerField(
                choices=[
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, 10),
                    (11, 11),
                ]
            ),
        ),
    ]
