# Generated by Django 5.0.6 on 2024-07-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homework", "0011_homework_subject_alter_homework_grade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homework",
            name="letter",
            field=models.CharField(
                choices=[("А", "А"), ("Б", "Б"), ("Г", "В"), ("Г", "Г")]
            ),
        ),
    ]
