# Generated by Django 5.0.6 on 2024-07-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homework", "0012_alter_homework_letter"),
    ]

    operations = [
        migrations.AddField(
            model_name="homework",
            name="group",
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)], default=0),
        ),
    ]
