# Generated by Django 5.0.6 on 2024-07-04 13:07

import homework.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("homework", "0013_homework_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homework",
            name="created_at",
            field=homework.models.DateTimeWithoutTZField(auto_now_add=True),
        ),
    ]
