# Generated by Django 5.0.6 on 2024-07-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homework", "0014_alter_homework_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homework",
            name="group",
            field=models.IntegerField(
                choices=[(-3, -3), (-2, -2), (-1, -1), (0, 0), (1, 1), (2, 2)],
                default=0,
            ),
        ),
    ]
