# Generated by Django 5.0.6 on 2024-07-08 17:42

import homework.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homework", "0015_alter_homework_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homework",
            name="created_at",
            field=homework.models.DateTimeWithoutTZField(
                auto_now_add=True, verbose_name="Дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="homework",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="homework",
            name="grade",
            field=models.IntegerField(
                choices=[
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, 10),
                    (11, 11),
                ],
                verbose_name="Класс",
            ),
        ),
        migrations.AlterField(
            model_name="homework",
            name="group",
            field=models.IntegerField(
                choices=[(-3, -3), (-2, -2), (-1, -1), (0, 0), (1, 1), (2, 2)],
                default=0,
                verbose_name="Группа",
            ),
        ),
        migrations.AlterField(
            model_name="homework",
            name="letter",
            field=models.CharField(
                choices=[("А", "А"), ("Б", "Б"), ("Г", "В"), ("Г", "Г")],
                verbose_name="Буква",
            ),
        ),
        migrations.AlterField(
            model_name="homework",
            name="subject",
            field=models.CharField(null=True, verbose_name="Предмет"),
        ),
    ]
