# Generated by Django 5.0.6 on 2024-07-09 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "homework",
            "0016_alter_homework_created_at_alter_homework_description_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="file",
            options={"verbose_name": "Файл", "verbose_name_plural": "Файлы"},
        ),
        migrations.AlterModelOptions(
            name="homework",
            options={
                "verbose_name": "Домашнее задание",
                "verbose_name_plural": "Домашние задания",
            },
        ),
        migrations.AlterModelOptions(
            name="image",
            options={
                "verbose_name": "Изображение",
                "verbose_name_plural": "Изображения",
            },
        ),
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(
                null=True,
                upload_to="files/homework/%Y/%d-%m/",
                verbose_name="Путь к файлу",
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="file_name",
            field=models.CharField(verbose_name="Название файлы"),
        ),
        migrations.AlterField(
            model_name="file",
            name="homework",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="homework.homework",
                verbose_name="Домашнее задание",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="homework",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="homework.homework",
                verbose_name="Домашнее задание",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(
                null=True,
                upload_to="img/homework/%Y/%d-%m/",
                verbose_name="Путь к изображению",
            ),
        ),
    ]
