# Generated by Django 5.0.6 on 2024-07-10 22:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homework", "0017_alter_file_options_alter_homework_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_done",
                    models.BooleanField(default=False, verbose_name="Выполнено"),
                ),
            ],
            options={
                "verbose_name": "Список ToDo",
                "verbose_name_plural": "Списки ToDo",
            },
        ),
        migrations.AddField(
            model_name="homework",
            name="todo",
            field=models.ManyToManyField(to="homework.todo"),
        ),
    ]
