# Generated by Django 5.0.6 on 2024-07-10 23:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homework", "0018_todo_homework_todo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homework",
            name="todo",
            field=models.ManyToManyField(related_name="homework", to="homework.todo"),
        ),
    ]
