# Generated by Django 5.0.6 on 2024-07-10 23:25

import homework.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("homework", "0019_alter_homework_todo"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="created_at",
            field=homework.models.DateTimeWithoutTZField(
                auto_now_add=True, default="2024-12-12", verbose_name="Дата создания"
            ),
            preserve_default=False,
        ),
    ]
