# Generated by Django 5.0.6 on 2024-07-10 23:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homework", "0020_todo_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homework",
            name="letter",
            field=models.CharField(
                choices=[("А", "А"), ("Б", "Б"), ("Г", "В"), ("Г", "Г")],
                verbose_name="Литера",
            ),
        ),
    ]
