# Generated by Django 5.0.6 on 2024-07-10 23:40

import homework.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("homework", "0001_initial_squashed_0021_alter_homework_letter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="created_at",
            field=homework.models.DateTimeWithoutTZField(
                auto_now_add=True, verbose_name="Дата создания"
            ),
        ),
    ]
