# Generated by Django 5.0.6 on 2024-07-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homework", "0022_alter_todo_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homework",
            name="todo",
            field=models.ManyToManyField(
                related_name="homework_todo", to="homework.todo"
            ),
        ),
    ]
