# Generated by Django 5.0.6 on 2024-07-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homework", "0023_alter_homework_todo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grade",
                    models.IntegerField(
                        choices=[
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                            (11, 11),
                        ],
                        verbose_name="Класс",
                    ),
                ),
                (
                    "letter",
                    models.CharField(
                        choices=[("А", "А"), ("Б", "Б"), ("Г", "В"), ("Г", "Г")],
                        verbose_name="Литера",
                    ),
                ),
                ("weekday", models.IntegerField(verbose_name="День недели")),
                ("lesson", models.IntegerField(verbose_name="Урок")),
                ("subject", models.CharField(verbose_name="Предмет")),
            ],
        ),
    ]
