# Generated by Django 5.0.6 on 2024-07-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homework", "0024_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="group",
            field=models.IntegerField(default=1, verbose_name="Группа"),
        ),
    ]
