# Generated by Django 5.0.6 on 2024-07-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homework", "0025_schedule_group"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="homework",
            index=models.Index(
                fields=["grade", "letter"], name="homework_ho_grade_d37973_idx"
            ),
        ),
    ]
