# Generated by Django 5.0.6 on 2024-08-03 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0028_alter_schedule_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='letter',
            field=models.CharField(choices=[('А', 'А'), ('Б', 'Б'), ('В', 'В'), ('Г', 'Г')], verbose_name='Литера'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='letter',
            field=models.CharField(choices=[('А', 'А'), ('Б', 'Б'), ('В', 'В'), ('Г', 'Г')], verbose_name='Литера'),
        ),
    ]
