# Generated by Django 5.0.6 on 2024-08-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0029_alter_homework_letter_alter_schedule_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='todo',
            field=models.ManyToManyField(null=True, related_name='homework_todo', to='homework.todo'),
        ),
    ]
