# Generated by Django 5.0.6 on 2024-08-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0030_alter_homework_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='todo',
            field=models.ManyToManyField(blank=True, related_name='homework_todo', to='homework.todo'),
        ),
    ]
