# Generated by Django 5.0.6 on 2024-08-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0031_alter_homework_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='telegram_file_id',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='telegram_file_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
