services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "${NGINX_CERT}:/etc/nginx/ssl/fullchain.pem"
      - "${NGINX_KEY}:/etc/nginx/ssl/privkey.pem"
    restart: unless-stopped
    depends_on:
      - db
      - redis
      - web
      - bot
    networks:
      - django-network

  db:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
       - django-network

  web:
    build: .
    command: bash -c "cd chtozadano &&
                      python manage.py migrate &&
                      python manage.py collectstatic --no-input &&
                      gunicorn --config gunicorn_config.py chtozadano.wsgi:application --preload"
    volumes:
      - .:/code
      - ./chtozadano/logs:/code/chtozadano/logs
    expose:
      - "8000"
    restart: unless-stopped
    depends_on:
      - db
      - redis
    links:
      - db:db
    networks:
       - django-network

  bot:
    build: .
    volumes:
      - .:/code
    command: bash -c "cd chtozadano &&
                      python telegram_bot"
    restart: unless-stopped
    depends_on:
      - db
      - redis
      - web
    expose:
      - "8000"
    networks:
      - django-network

  redis:
    image: redis:7.4.0-alpine
    hostname: redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - django-network

  celery-beat:
    build: .
    command: bash -c "cd chtozadano &&
                      celery -A celery_app beat --loglevel=info"
    volumes:
      - .:/code
    restart: unless-stopped
    depends_on:
      - web
    networks:
      - django-network

  celery-worker:
    build: .
    command: bash -c "cd chtozadano &&
                      celery -A celery_app worker --loglevel=info"
    volumes:
      - .:/code
    depends_on:
      - redis
    networks:
      - django-network

volumes:
  postgres_data:
  redis_data:

networks:
  django-network:
    driver: bridge
