services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/cert.pem:/etc/cert.pem"
      - "./nginx/key.pem:/etc/key.pem"
    depends_on:
      - bot
    networks:
      - django-network

  db:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
       - django-network

  web:
    build: .
    command: bash -c "cd chtozadano &&
                      python manage.py migrate &&
                      python manage.py collectstatic --no-input &&
                      gunicorn --config gunicorn_config.py chtozadano.wsgi:application"
    volumes:
      - .:/code
    expose:
      - "8000"
    depends_on:
      - db
    links:
      - db:db
    restart: always
    networks:
       - django-network

  bot:
    build: .
    volumes:
      - .:/code
    command: python bot.py
    depends_on:
      - web
    restart: always
    networks:
      - django-network

volumes:
  postgres_data:

networks:
  django-network:
    driver: bridge
