[tool.flake8]
ignore = ["E203", "PL123", "W503"]
inline-quotes = '"'
docstring-quotes = '"'
exclude = ".git,__pycache__,docs/source/conf.py,old,build,dist,migrations"
import-order-style = "google"
application-import-names = ["users", "homework", "analytics"]
max-line-length = 79
per-file-ignores = [
    "chtozadano/scripts/add_schedule_script.py: T201"
]

[tool.black]
line-length = 79
exclude = "migrations"
diff = true
color = true