# Generated by Django 5.0.6 on 2024-08-01 02:17

import colorfield.fields
import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("homework", "0028_alter_schedule_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="BecomeAdmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grade",
                    models.IntegerField(
                        choices=[
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                            (11, 11),
                        ],
                        verbose_name="Класс",
                    ),
                ),
                (
                    "letter",
                    models.CharField(
                        choices=[("А", "А"), ("Б", "Б"), ("Г", "В"), ("Г", "Г")],
                        verbose_name="Литера",
                    ),
                ),
                (
                    "group",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2)], verbose_name="Группа"
                    ),
                ),
                ("first_name", models.CharField(verbose_name="Имя")),
                ("last_name", models.CharField(verbose_name="Фамилия")),
                (
                    "telegram_id",
                    models.CharField(blank=True, null=True, verbose_name="Телеграм id"),
                ),
            ],
            options={
                "verbose_name": "Заявка на администратора",
                "verbose_name_plural": "Заявки на администратора",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="server_user",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "grade",
                    models.IntegerField(
                        choices=[
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                            (11, 11),
                        ],
                        verbose_name="Класс",
                    ),
                ),
                (
                    "letter",
                    models.CharField(
                        choices=[("А", "А"), ("Б", "Б"), ("Г", "В"), ("Г", "Г")],
                        verbose_name="Буква",
                    ),
                ),
                (
                    "telegram_id",
                    models.CharField(blank=True, null=True, verbose_name="Телеграм id"),
                ),
                (
                    "group",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2)], default=1, verbose_name="Группа"
                    ),
                ),
                (
                    "notebook",
                    models.TextField(blank=True, null=True, verbose_name="Заметки"),
                ),
                (
                    "notebook_color",
                    colorfield.fields.ColorField(
                        default="#FF0000", image_field=None, max_length=25, samples=None
                    ),
                ),
                (
                    "chat_mode",
                    models.BooleanField(default=False, verbose_name="Режим чата"),
                ),
                (
                    "todo",
                    models.ManyToManyField(
                        blank=True, related_name="user_todo", to="homework.todo"
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.CreateModel(
            name="SignIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram_id",
                    models.CharField(blank=True, null=True, verbose_name="Telegram ID"),
                ),
                (
                    "confirmation_code",
                    models.CharField(
                        blank=True, null=True, verbose_name="Код идентификации"
                    ),
                ),
                (
                    "created_at",
                    users.models.DateTimeWithoutTZField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                ("name", models.CharField(blank=True, null=True, verbose_name="Имя")),
                (
                    "singning_user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="users.user",
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Идентификация",
                "verbose_name_plural": "Идентификации",
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["grade", "letter"], name="users_user_grade_7a324d_idx"
            ),
        ),
    ]
