# Generated by Django 5.0.6 on 2024-07-10 23:41

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("users", "0001_initial"),
        ("users", "0002_signin"),
        ("users", "0003_rename_user_id_signin_user"),
        ("users", "0004_todo"),
        ("users", "0005_signin_name"),
        ("users", "0006_alter_signin_name_alter_todo_is_done_and_more"),
        ("users", "0007_rename_user_signin_singning_user"),
        ("users", "0008_alter_user_user"),
        ("users", "0009_alter_user_grade_alter_user_letter"),
        ("users", "0010_user_group"),
        ("users", "0011_alter_signin_telegram_id"),
        ("users", "0012_alter_signin_telegram_id"),
        ("users", "0013_alter_user_telegram_id"),
        ("users", "0014_becomeadmin"),
        ("users", "0015_alter_signin_created_at"),
        ("users", "0016_user_chat_mode"),
        ("users", "0017_alter_user_telegram_id"),
        ("users", "0018_alter_becomeadmin_telegram_id"),
        ("users", "0019_alter_signin_options_alter_todo_options_and_more"),
        ("users", "0020_signin_todo_delete_todo"),
        ("users", "0021_remove_signin_todo_user_todo"),
        ("users", "0022_alter_user_todo"),
    ]

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("homework", "0001_initial"),
        ("homework", "0017_alter_file_options_alter_homework_options_and_more"),
        ("homework", "0018_todo_homework_todo"),
        ("homework", "0019_alter_homework_todo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="server_user",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "grade",
                    models.IntegerField(
                        choices=[
                            (1, 1),
                            (2, 2),
                            (3, 3),
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                            (11, 11),
                        ],
                        verbose_name="Класс",
                    ),
                ),
                (
                    "letter",
                    models.CharField(
                        choices=[("А", "А"), ("Б", "Б"), ("Г", "В"), ("Г", "В")],
                        verbose_name="Буква",
                    ),
                ),
                (
                    "telegram_id",
                    models.CharField(blank=True, null=True, verbose_name="Телеграм id"),
                ),
                (
                    "notebook",
                    models.TextField(blank=True, null=True, verbose_name="Заметки"),
                ),
                (
                    "homework",
                    models.ManyToManyField(
                        blank=True,
                        related_name="author",
                        to="homework.homework",
                        verbose_name="Домашнее задание",
                    ),
                ),
                (
                    "group",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2)], default=1, verbose_name="Группа"
                    ),
                ),
                (
                    "chat_mode",
                    models.BooleanField(default=False, verbose_name="Режим чата"),
                ),
                (
                    "todo",
                    models.ManyToManyField(related_name="user", to="homework.todo"),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.CreateModel(
            name="BecomeAdmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grade",
                    models.IntegerField(
                        choices=[
                            (1, 1),
                            (2, 2),
                            (3, 3),
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                            (11, 11),
                        ]
                    ),
                ),
                (
                    "letter",
                    models.CharField(
                        choices=[("А", "А"), ("Б", "Б"), ("Г", "В"), ("Г", "В")]
                    ),
                ),
                ("group", models.CharField(choices=[(1, 1), (2, 2)])),
                ("first_name", models.CharField()),
                ("last_name", models.CharField()),
                ("telegram_id", models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SignIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram_id",
                    models.CharField(blank=True, null=True, verbose_name="Telegram ID"),
                ),
                (
                    "confirmation_code",
                    models.CharField(
                        blank=True, null=True, verbose_name="Код подтверждения"
                    ),
                ),
                (
                    "created_at",
                    users.models.DateTimeWithoutTZField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "singning_user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="users.user",
                        verbose_name="Пользователб",
                    ),
                ),
                ("name", models.CharField(blank=True, null=True, verbose_name="Имя")),
            ],
            options={
                "verbose_name": "Sign in",
                "verbose_name_plural": "Sign in",
            },
        ),
    ]
