# Generated by Django 5.0.6 on 2024-06-29 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("homework", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("grade", models.IntegerField(blank=True, null=True)),
                ("letter", models.CharField(blank=True, null=True)),
                ("telegram_id", models.IntegerField(blank=True, null=True)),
                ("notebook", models.TextField(blank=True, null=True)),
                (
                    "homework",
                    models.ManyToManyField(
                        blank=True, related_name="author", to="homework.homework"
                    ),
                ),
            ],
        ),
    ]
