# Generated by Django 5.0.6 on 2024-08-03 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='becomeadmin',
            name='letter',
            field=models.CharField(choices=[('А', 'А'), ('Б', 'Б'), ('В', 'В'), ('Г', 'Г')], verbose_name='Литера'),
        ),
        migrations.AlterField(
            model_name='user',
            name='letter',
            field=models.CharField(choices=[('А', 'А'), ('Б', 'Б'), ('В', 'В'), ('Г', 'Г')], verbose_name='Буква'),
        ),
    ]
