# Generated by Django 5.0.6 on 2024-08-11 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_becomeadmin_letter_alter_user_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_quotes',
            field=models.BooleanField(default=False, verbose_name='Режим цитат'),
        ),
    ]
