# Generated by Django 5.0.6 on 2024-08-12 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_show_quotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='show_quotes',
            field=models.BooleanField(default=True, verbose_name='Режим цитат'),
        ),
    ]
