# Generated by Django 5.0.6 on 2024-08-12 16:36

import users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_show_quotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='becomeadmin',
            name='created_at',
            field=users.models.DateTimeWithoutTZField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
    ]
