# Generated by Django 5.0.6 on 2024-06-29 21:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_todo"),
    ]

    operations = [
        migrations.AddField(
            model_name="signin",
            name="name",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
