# Generated by Django 5.0.6 on 2024-08-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_becomeadmin_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chat_mode',
            field=models.BooleanField(default=True, verbose_name='Режим чата'),
        ),
    ]
