# Generated by Django 5.0.6 on 2024-08-29 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_chat_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='notebook',
        ),
        migrations.RemoveField(
            model_name='user',
            name='notebook_color',
        ),
    ]
