# Generated by Django 5.0.6 on 2024-06-30 13:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_signin_name_alter_todo_is_done_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="signin",
            old_name="user",
            new_name="singning_user",
        ),
    ]
