# Generated by Django 5.0.6 on 2024-08-27 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_chat_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fast_hw',
            field=models.BooleanField(default=True, verbose_name='Режим быстрого добавления дз'),
        ),
    ]
