# Generated by Django 5.0.6 on 2024-08-29 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_notebook_remove_user_notebook_color'),
        ('users', '0007_user_fast_hw'),
    ]

    operations = [
    ]
