# Generated by Django 5.0.6 on 2024-09-11 21:55

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_merge_20240829_2302'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('analytics', django.db.models.manager.Manager()),
            ],
        ),
    ]
