# Generated by Django 5.0.6 on 2024-07-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_user_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="grade",
            field=models.IntegerField(
                choices=[
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, 10),
                    (11, 11),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="letter",
            field=models.CharField(
                choices=[("А", "А"), ("Б", "Б"), ("Г", "В"), ("Г", "В")]
            ),
        ),
    ]
