# Generated by Django 5.0.6 on 2024-07-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_alter_user_grade_alter_user_letter"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="group",
            field=models.IntegerField(choices=[(1, 1), (2, 2)], default=1),
        ),
    ]
