# Generated by Django 5.0.6 on 2024-07-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_user_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signin",
            name="telegram_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
