# Generated by Django 5.0.6 on 2024-07-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_alter_signin_telegram_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="telegram_id",
            field=models.CharField(),
        ),
    ]
