# Generated by Django 5.0.6 on 2024-07-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_alter_user_telegram_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="BecomeAdmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grade",
                    models.IntegerField(
                        choices=[
                            (1, 1),
                            (2, 2),
                            (3, 3),
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                            (11, 11),
                        ]
                    ),
                ),
                (
                    "letter",
                    models.CharField(
                        choices=[("А", "А"), ("Б", "Б"), ("Г", "В"), ("Г", "В")]
                    ),
                ),
                ("group", models.CharField(choices=[(1, 1), (2, 2)])),
                ("first_name", models.CharField()),
                ("last_name", models.CharField()),
                ("telegram_id", models.CharField()),
            ],
        ),
    ]
