# Generated by Django 5.0.6 on 2024-07-04 13:07

import users.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_becomeadmin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signin",
            name="created_at",
            field=users.models.DateTimeWithoutTZField(auto_now_add=True),
        ),
    ]
