# Generated by Django 5.0.6 on 2024-07-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0015_alter_signin_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="chat_mode",
            field=models.BooleanField(default=False),
        ),
    ]
