# Generated by Django 5.0.6 on 2024-07-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_user_chat_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="telegram_id",
            field=models.CharField(blank=True, null=True),
        ),
    ]
