# Generated by Django 5.0.6 on 2024-07-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0017_alter_user_telegram_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="becomeadmin",
            name="telegram_id",
            field=models.CharField(blank=True, null=True),
        ),
    ]
