# Generated by Django 5.0.6 on 2024-07-09 12:20

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homework", "0017_alter_file_options_alter_homework_options_and_more"),
        ("users", "0018_alter_becomeadmin_telegram_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="signin",
            options={"verbose_name": "Sign in", "verbose_name_plural": "Sign in"},
        ),
        migrations.AlterModelOptions(
            name="todo",
            options={
                "verbose_name": "Список ToDo",
                "verbose_name_plural": "Списки ToDo",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AlterField(
            model_name="signin",
            name="confirmation_code",
            field=models.CharField(
                blank=True, null=True, verbose_name="Код подтверждения"
            ),
        ),
        migrations.AlterField(
            model_name="signin",
            name="created_at",
            field=users.models.DateTimeWithoutTZField(
                auto_now_add=True, verbose_name="Дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="signin",
            name="name",
            field=models.CharField(blank=True, null=True, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="signin",
            name="singning_user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="users.user",
                verbose_name="Пользователб",
            ),
        ),
        migrations.AlterField(
            model_name="signin",
            name="telegram_id",
            field=models.CharField(blank=True, null=True, verbose_name="Telegram ID"),
        ),
        migrations.RemoveField(
            model_name="todo",
            name="homework",
        ),
        migrations.AlterField(
            model_name="todo",
            name="is_done",
            field=models.BooleanField(default=False, verbose_name="Выполнено"),
        ),
        migrations.RemoveField(
            model_name="todo",
            name="user",
        ),
        migrations.AlterField(
            model_name="user",
            name="chat_mode",
            field=models.BooleanField(default=False, verbose_name="Режим чата"),
        ),
        migrations.AlterField(
            model_name="user",
            name="grade",
            field=models.IntegerField(
                choices=[
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, 10),
                    (11, 11),
                ],
                verbose_name="Класс",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="group",
            field=models.IntegerField(
                choices=[(1, 1), (2, 2)], default=1, verbose_name="Группа"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="homework",
            field=models.ManyToManyField(
                blank=True,
                related_name="author",
                to="homework.homework",
                verbose_name="Домашнее задание",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="letter",
            field=models.CharField(
                choices=[("А", "А"), ("Б", "Б"), ("Г", "В"), ("Г", "В")],
                verbose_name="Буква",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="notebook",
            field=models.TextField(blank=True, null=True, verbose_name="Заметки"),
        ),
        migrations.AlterField(
            model_name="user",
            name="telegram_id",
            field=models.CharField(blank=True, null=True, verbose_name="Телеграм id"),
        ),
        migrations.AlterField(
            model_name="user",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="server_user",
                serialize=False,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddField(
            model_name="todo",
            name="homework",
            field=models.ManyToManyField(
                to="homework.homework", verbose_name="Домашнее задание"
            ),
        ),
        migrations.AddField(
            model_name="todo",
            name="user",
            field=models.ManyToManyField(to="users.user", verbose_name="Пользователь"),
        ),
    ]
