# Generated by Django 5.0.6 on 2024-07-10 22:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homework", "0018_todo_homework_todo"),
        ("users", "0019_alter_signin_options_alter_todo_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="signin",
            name="todo",
            field=models.ManyToManyField(to="homework.todo"),
        ),
        migrations.DeleteModel(
            name="Todo",
        ),
    ]
