# Generated by Django 5.0.6 on 2024-07-10 23:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homework", "0019_alter_homework_todo"),
        ("users", "0020_signin_todo_delete_todo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="signin",
            name="todo",
        ),
        migrations.AddField(
            model_name="user",
            name="todo",
            field=models.ManyToManyField(related_name="User", to="homework.todo"),
        ),
    ]
