# Generated by Django 5.0.6 on 2024-07-10 23:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homework", "0019_alter_homework_todo"),
        ("users", "0021_remove_signin_todo_user_todo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="todo",
            field=models.ManyToManyField(related_name="user", to="homework.todo"),
        ),
    ]
