# Generated by Django 5.0.6 on 2024-07-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homework", "0023_alter_homework_todo"),
        ("users", "0001_initial_squashed_0022_alter_user_todo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="todo",
            field=models.ManyToManyField(related_name="user_todo", to="homework.todo"),
        ),
    ]
