# Generated by Django 5.0.6 on 2024-07-12 17:34

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0023_alter_user_todo"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notebook_color",
            field=colorfield.fields.ColorField(
                default="#FF0000", image_field=None, max_length=25, samples=None
            ),
        ),
    ]
