# Generated by Django 5.0.6 on 2024-07-26 01:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homework", "0025_schedule_group"),
        ("users", "0024_user_notebook_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="becomeadmin",
            name="grade",
            field=models.IntegerField(
                choices=[
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, 10),
                    (11, 11),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="grade",
            field=models.IntegerField(
                choices=[
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, 10),
                    (11, 11),
                ],
                verbose_name="Класс",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="todo",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="user_todo", to="homework.todo"
            ),
        ),
    ]
