# Generated by Django 5.0.6 on 2024-07-30 21:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homework", "0026_homework_homework_ho_grade_d37973_idx"),
        (
            "users",
            "0001_initial_squashed_0022_alter_user_todo_squashed_0031_alter_user_options_alter_becomeadmin_letter_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["grade", "letter"], name="users_user_grade_7a324d_idx"
            ),
        ),
    ]
