# Generated by Django 5.0.6 on 2024-07-31 02:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0032_user_users_user_grade_7a324d_idx"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="homework",
        ),
    ]
