# Generated by Django 5.0.6 on 2024-09-11 21:26

import homework.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeworks_add_site', models.IntegerField(default=0)),
                ('homeworks_edit_site', models.IntegerField(default=0)),
                ('homeworks_delete_site', models.IntegerField(default=0)),
                ('homeworks_add_bot', models.IntegerField(default=0)),
                ('homeworks_edit_bot', models.IntegerField(default=0)),
                ('homeworks_delete_bot', models.IntegerField(default=0)),
                ('active_class_name', models.CharField(blank=True, null=True)),
                ('active_class_homeworks', models.IntegerField(default=0)),
                ('cron_homeworks_deleted', models.IntegerField(default=0)),
                ('cron_todo_deleted', models.IntegerField(default=0)),
                ('created_at', homework.models.DateTimeWithoutTZField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsersAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_users_site', models.IntegerField(default=0)),
                ('new_users_bot', models.IntegerField(default=0)),
                ('new_code_verifications', models.IntegerField(default=0)),
                ('created_at', homework.models.DateTimeWithoutTZField(auto_now_add=True)),
            ],
        ),
    ]
