name: bot CI

on:
  push:
    branches: ["bot"]
  pull_request:
    branches: ["bot"]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10"]
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - run: pip install -r requirements/dev.txt
    - name: Linting | Black
      run: |
        black --check chtozadano/
    - name: Linting | Flake8
      run: |
        flake8 --verbose chtozadano/
